# Coding CI/CD 配置文件
# 自动构建并部署到服务器

# 触发条件
trigger:
  push:
    branches:
      - main
      - master

# 流水线阶段
stages:
  - stage: 构建镜像
    displayName: '构建 Docker 镜像'
    jobs:
      - job: build_backend
        displayName: '构建后端镜像'
        steps:
          - name: checkout
            uses: coding/checkout@v1

          - name: build_backend_image
            uses: coding/docker-build@v1
            with:
              dockerfile: ./backend/Dockerfile
              context: ./backend
              image: anita-backend
              tag: ${{ env.GIT_COMMIT_SHORT }}
              registry: ${{ env.DOCKER_REGISTRY }}
              username: ${{ env.DOCKER_USERNAME }}
              password: ${{ env.DOCKER_PASSWORD }}

      - job: build_frontend
        displayName: '构建前端镜像'
        steps:
          - name: checkout
            uses: coding/checkout@v1

          - name: build_frontend_image
            uses: coding/docker-build@v1
            with:
              dockerfile: ./frontend/Dockerfile
              context: ./frontend
              image: anita-frontend
              tag: ${{ env.GIT_COMMIT_SHORT }}
              registry: ${{ env.DOCKER_REGISTRY }}
              username: ${{ env.DOCKER_USERNAME }}
              password: ${{ env.DOCKER_PASSWORD }}

  - stage: 部署应用
    displayName: '部署到服务器'
    jobs:
      - job: deploy
        displayName: 'SSH 部署'
        steps:
          - name: checkout
            uses: coding/checkout@v1

          - name: deploy_to_server
            uses: coding/ssh-deploy@v1
            with:
              host: ${{ env.SERVER_HOST }}
              port: ${{ env.SERVER_PORT }}
              username: ${{ env.SERVER_USER }}
              password: ${{ env.SERVER_PASSWORD }}
              # 或使用 SSH 密钥
              # private_key: ${{ env.SSH_PRIVATE_KEY }}
              script: |
                cd /opt/anita-project
                git pull origin main
                docker-compose pull
                docker-compose up -d --force-recreate
                docker system prune -f

# 环境变量（在 Coding 项目设置中配置）
# SERVER_HOST: 服务器IP
# SERVER_PORT: SSH端口（默认22）
# SERVER_USER: SSH用户名
# SERVER_PASSWORD: SSH密码
# DOCKER_REGISTRY: Docker镜像仓库地址（可选）
# DOCKER_USERNAME: Docker用户名（可选）
# DOCKER_PASSWORD: Docker密码（可选）
